export const Cities =
[
  { value: 1, label: 'Tel Aviv' },
  { value: 2, label: 'Haifa' },
  { value: 3, label: 'Jerusalem' },
  { value: 4, label: 'Rishon LeZion' },
  { value: 5, label: 'Petah Tikva' },
  { value: 6, label: 'Ashdod' },
  { value: 7, label: 'Netanya' },
  { value: 8, label: 'Beer Sheva' },
  { value: 9, label: 'Bnei Brak' },
  { value: 10, label: 'Holon' },
  { value: 11, label: 'Bat Yam' },
  { value: 12, label: 'Ramat Gan' },
  { value: 13, label: 'Ashkelon' },
  { value: 14, label: 'Herzliya' },
  { value: 15, label: 'Kfar Saba' },
  { value: 16, label: 'Ranana' },
  { value: 17, label: 'Modien' },
  { value: 18, label: 'Nahariya' },
  { value: 19, label: 'Beit Shemesh' },
  { value: 20, label: 'Lod' },
  { value: 22, label: 'Hod HaSharon' },
  { value: 23, label: 'Ashdod Yam' },
  { value: 25, label: 'Kiryat Gat' },
  { value: 26, label: 'Safed' },
  { value: 27, label: 'Eilat' },
  { value: 28, label: 'Dimona' },
  { value: 31, label: 'Nesher' },
  { value: 33, label: 'Or Yehuda' },
  { value: 35, label: 'Tiberias' },
  { value: 36, label: 'Kiryat Shmona' },
  { value: 37, label: 'Tirat Carmel' },
  { value: 38, label: 'Rosh HaAyin' },
  { value: 39, label: 'Ramat HaSharon' },
  { value: 40, label: 'Qalansawe' },
  { value: 41, label: 'Kafr Qasim' },
  { value: 42, label: 'Tamra' },
  { value: 43, label: 'Kiryat Yam' },
  { value: 44, label: 'Givatayim' },
  { value: 45, label: 'Eilabun' },
  { value: 46, label: 'Kafr Manda' },
  { value: 48, label: 'Sakhnin' },
  { value: 49, label: 'Yehud' },
  { value: 50, label: 'Umm al-Fahm' },
  { value: 51, label: 'Afula' },
  { value: 53, label: 'Kiryat Motzkin' },
  { value: 54, label: 'Ofakim' },
  { value: 55, label: 'Karmiel' },
  { value: 56, label: 'Nof HaGalil'} ,
  { value: 57, label: 'Shfaram'}, 
  {value:58, label : 'Fassuta'}
];
  